name: ci

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/**.md"
      - "**/LICENSE"
      - "**/.gitignore"
      - "**/.github/ISSUE_TEMPLATE/**"
      - "**/.config/**"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**/**.md"
      - "**/LICENSE"
      - "**/.gitignore"
      - "**/.github/ISSUE_TEMPLATE/**"
      - "**/.config/**"

jobs:
  core:
    uses: blackportal-ai/infra/.github/workflows/core.yml@master
